name: 'Mattermost Notify'
description: 'Notify other commit actions result via Mattermost'
inputs:
  mattermost-access-token:
    description: 'Access token for Mattermost'
    required: true
  repo-url:
    description: 'Github repository URL'
    required: true
  commit-sha:
    description: 'Github commit SHA'
    required: true
  check-run-name:
    description: 'The Check Run name'
    required: true
  check-run-conclusion:
    description: 'The Check Run conclusion'
    required: true
  check-run-url:
    description: 'The Check Run URL'
    required: true
  check-run-output-title:
    description: 'The Check Run title'
    required: true
  check-run-output-text:
    description: 'The Check Run text'
    required: true
  check-run-output-summary:
    description: 'The Check Run summary'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mattermost-access-token }}
    - ${{ inputs.repo-url }}
    - ${{ inputs.commit-sha }}
    - ${{ inputs.check-run-name }}
    - ${{ inputs.check-run-conclusion }}
    - ${{ inputs.check-run-url }}
    - ${{ inputs.check-run-output-title }}
    - ${{ inputs.check-run-output-text }}
    - ${{ inputs.check-run-output-summary }}
