name: 'Mattermost Notify'
description: 'Notify other commit actions result via Mattermost'
inputs:
  access-token:
    description: 'Access token for Mattermost'
    required: true
  commit-url:
    description: 'Github commit URL'
    required: true
  commit-author-username:
    description: 'Github commit author username'
    required: true
  commit-author-email:
    description: 'Github commit author email'
    required: true
  commit-message:
    description: 'Github commit message'
    required: true
  job-output:
    description: 'The output of the Github Action job that needs to be notified'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MATTERMOST_PERSONAL_ACCESS_TOKEN: ${{ inputs.access-token }}
    COMMIT_URL: ${{ inputs.commit-url }}
    COMMIT_AUTHOR_USERNAME: ${{ inputs.commit-author-username }}
    COMMIT_AUTHOR_EMAIL: ${{ inputs.commit-author-email }}
    COMMIT_MESSAGE: ${{ inputs.commit-message }}
    TEST_JOB_OUTPUT: ${{ inputs.job-output }}