#!/bin/sh -l

echo 'Running entrypoint'

MATTERMOST_ACCESS_TOKEN=${1} \
MATTERMOST_INCOMING_WEBHOOK_URL=${2} \
MATTERMOST_CHANNEL_NAME=${3} \
COMMIT_URL=${4} \
COMMIT_AUTHOR_USERNAME=${5} \
COMMIT_AUTHOR_EMAIL=${6} \
COMMIT_MESSAGE=${7} \
STATUS_CONCLUSION=${8} \
STATUS_URL=${9} \
STATUS_NAME=${10} \
STATUS_DESCRIPTION=${11} \
go run /main.go

echo 'Running entrypoint done'
